timeout_min: 2880 # [1day=1440, 2day=2880, 5day=7200]
nodes: 1
cpus_per_task: 48
tasks_per_node: 1
mem_per_cpu: null

# default value
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
gpus_per_node: null
mem_gb: 128


name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: allcpu,cpu,classicgpu
qos: null
comment: null
constraint: null
exclude: null
gres: null
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
account: null
signal_delay_s: 120
max_num_timeout: 0
additional_parameters: {}
array_parallelism: 256
setup: null
srun_args: null